services:
  postgresql:
    image: postgres:16.0
    volumes:
      - todo-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chats
  app:
    image: node:20-alpine
    command: sh -c "sleep 3; yarn install; yarn run migrate; yarn run seed; yarn run watch"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://postgres:secret@postgresql:5432/chats?schema=public
    depends_on:
      - postgresql

volumes:
  todo-postgresql-data: